import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Slide1 from "@/components/Static/Slides/Slide-1";
import Slide2 from "@/components/Static/Slides/Slide-2";
import Slide3 from "@/components/Static/Slides/Slide-3";
import Slide4 from "@/components/Static/Slides/Slide-4";
import Slide5 from "@/components/Static/Slides/Slide-5";
import Slide6 from "@/components/Static/Slides/Slide-6";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ pageTitle }) {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <div id="min-navbar" className="d-flex flex-row flex-wrap justify-content-end my-4">
        <p className="px-2 hover-underline-black"><i className="bi bi-house-door-fill mx-2"></i>Home</p>
        <p className="px-2 hover-underline-black"><i className="bi bi-activity mx-2"></i>Features</p>
        <p className="px-2 hover-underline-black"><i className="bi bi-tag mx-2"></i>About</p>
        <p className="px-2 hover-underline-black"><i className="bi bi-joystick mx-2"></i>News</p>
        <p className="px-2 me-3 hover-underline-black"><i className="bi bi-question-circle-fill mx-2"></i>Q&A</p>
      </div>
      <Slide1 />
      <Slide2 />
      <Slide3 />
      <Slide4 />
      <Slide5 />
      <Slide6 />
    </>
  );
}
